services:
  - type: web
    name: viralpulse-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://ai-marketing-assistant-osx0.onrender.com/api/auth/google/callback
      - key: FRONTEND_URL
        value: https://viral-craft-forntend.vercel.app
      - key: BACKEND_URL
        value: https://ai-marketing-assistant-osx0.onrender.com
      - key: ML_SERVICE_URL
        value: https://viralpulse-ml.onrender.com

  - type: web
    name: viralpulse-ml
    runtime: python
    rootDir: ml
    buildCommand: pip install -r requirements.txt
    startCommand: python inference/service.py
    envVars:
      - key: PORT
        value: 5001

  - type: web
    name: viralpulse-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist